name: CI/CD Sandbox Hosting (Kuronekosan)

on:
  release:
    types: [ prereleased ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Im getting latest code, Master.
      uses: actions/checkout@v3
    - name: Setup PHP right now, nyaa~
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install Dependencies, UwU~
      run: composer update
    - name: Directory Permissions, please waiittt....
      run: chmod -R 777 storage bootstrap/cache
    - name: Zipping the folder, meow~
      run: for dir in */; do ( zip -r "${dir%/}".zip "$dir" && rm -rf "${dir%/}") done
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.LARAVEL_HOSTING_SERVER }}
        username: ${{ secrets.LARAVEL_HOSTING_USER_FTP }}
        password: ${{ secrets.LARAVEL_HOSTING_PASS_FTP }}
        server-dir: ./swadana/
        exclude: |
          **/.git*
          **/.git*/**
          .env
    - name: Connecting to Server via SSH, meow~
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: for dir in swadana/*/; do ( rm -rf "${dir%/}" ) done && for zip in swadana/*.zip; do ( unzip -o "$zip" -d swadana/ && rm -rf "$zip") done && cd swadana/ && composer update && php artisan optimize && php artisan storage:link && sudo chown -R sleepyboy:www-data ../swadana && sudo find ../swadana -type f -exec chmod 664 {} \; && sudo find ../swadana -type d -exec chmod 775 {} \; && sudo chgrp -R www-data storage bootstrap/cache && sudo chmod -R ug+rwx storage bootstrap/cache
        host: ${{ secrets.LARAVEL_HOSTING_SERVER }}
        port: 22
        username: ${{ secrets.LARAVEL_HOSTING_USER_SSH }}
        privateKey: ${{ secrets.LARAVEL_HOSTING_PRIVATE_KEY }}
